// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_sub: dynamic(() => import("./HeroSub")),
  player_setup: dynamic(() => import("./PlayerSetup")),
};
